// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // SQLite: use file:./prisma/mindlog.db (or set DATABASE_URL="file:./prisma/mindlog.db")
    url:
      process.env["DATABASE_URL"]?.startsWith("file:")
        ? process.env["DATABASE_URL"]
        : "file:./prisma/mindlog.db",
  },
});
